[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  command = "npm run dev:vite"
  port = 8888
  targetPort = 5173
  functions = "netlify/functions"

[functions."daily-team-email"]
  schedule = "0 0,1 * * *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200