[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  framework = "vite"
  command = "npm run dev:vite"
  port = 8888
  targetPort = 5173
  functions = "netlify/functions"

[functions."daily-team-email"]
  schedule = "@daily"

[functions."daily-partner-stats-7"]
  schedule = "0 1 * * *"

[functions."daily-partner-stats-30"]
  schedule = "10 1 * * *"

[functions."daily-partner-stats-90"]
  schedule = "20 1 * * *"

[functions."daily-partner-stats-180"]
  schedule = "30 1 * * *"

[functions."daily-partner-stats-365"]
  schedule = "40 1 * * *"

[[redirects]]
  from = "/stats"
  to = "/stats.html"
  status = 200

[[redirects]]
  from = "/stats/"
  to = "/stats.html"
  status = 200

[[redirects]]
  from = "/stats/*"
  to = "/stats.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200