ALTER TABLE events
  ADD COLUMN IF NOT EXISTS venue_instagram TEXT,
  ADD COLUMN IF NOT EXISTS venue_google_url TEXT,
  ADD COLUMN IF NOT EXISTS venue_lat DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS venue_lng DOUBLE PRECISION;
